id: P007904
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20549
  title: སྲིད་པའི་རྩེད་རིགས་མཛེས་སྡུག་གར་གྱི་སྟངས་སྟབས།
  author: ''
  volumes:
    7906b4e3b4b5494689fb0fc05f299665:
      image_group_id: I8LS20551
      title: ''
      volume_number: 1
      total_pages: 170
ebook_metadata:
  title: སྲིད་པའི་རྩེད་རིགས་མཛེས་སྡུག་གར་གྱི་སྟངས་སྟབས།
  author: ''
  sku: P007904
  cover: cover.jpg
  layers:
  - pagination
